import { ACCENTS } from '../data/accents.js'

// Field types understood by FieldInput.jsx:
//   text | textarea | date | boolean | select | colorSwatch | image | file

export const sections = [
  {
    key: 'hero',
    label: 'Hero Section',
    type: 'singleton',
    table: 'hero',
    fields: [
      { name: 'name', label: 'Full name', type: 'text' },
      { name: 'certificate_name', label: 'Certificate name (shown on hover)', type: 'text' },
      { name: 'initials', label: 'Initials (logo badge)', type: 'text' },
      { name: 'tagline', label: 'Tagline', type: 'textarea' },
      { name: 'roles', label: 'Rotating roles (comma separated)', type: 'text' },
      { name: 'photo_url', label: 'Portrait photo', type: 'image', bucket: 'site-media' },
      { name: 'reader_card_no', label: 'Reader card number', type: 'text' },
      { name: 'programme', label: 'Programme', type: 'text' },
      { name: 'institution', label: 'Institution', type: 'text' },
      { name: 'status', label: 'Status', type: 'text' },
    ],
  },
  {
    key: 'about',
    label: 'About Me',
    type: 'singleton',
    table: 'about',
    fields: [
      { name: 'paragraph_1', label: 'Paragraph 1', type: 'textarea', rows: 4 },
      { name: 'paragraph_2', label: 'Paragraph 2', type: 'textarea', rows: 4 },
      { name: 'based_in', label: 'Based in', type: 'text' },
      { name: 'focus', label: 'Focus', type: 'text' },
      { name: 'degree_status', label: 'Degree status', type: 'text' },
      { name: 'languages', label: 'Languages', type: 'text' },
    ],
  },
  {
    key: 'education',
    label: 'Education Timeline',
    type: 'list',
    table: 'education',
    orderField: 'sort_order',
    orderAscending: true,
    searchFields: ['degree', 'institution', 'period'],
    primary: 'degree',
    secondary: 'institution',
    fields: [
      { name: 'degree', label: 'Degree', type: 'text', required: true },
      { name: 'institution', label: 'Institution', type: 'text' },
      { name: 'faculty', label: 'Faculty', type: 'text' },
      { name: 'dorm', label: 'Dorm / Hall', type: 'text' },
      { name: 'period', label: 'Period', type: 'text' },
      { name: 'code', label: 'Call number / code', type: 'text' },
      { name: 'status', label: 'Status line', type: 'text' },
      { name: 'highlight', label: 'Highlight this status', type: 'boolean' },
      { name: 'details', label: 'Details', type: 'textarea' },
      { name: 'result', label: 'Result / GPA', type: 'text' },
    ],
  },
  {
    key: 'skills',
    label: 'Skills',
    type: 'list',
    table: 'skills',
    orderField: 'sort_order',
    orderAscending: true,
    searchFields: ['group_name', 'items'],
    primary: 'group_name',
    secondary: 'code',
    fields: [
      { name: 'group_name', label: 'Category name', type: 'text', required: true },
      { name: 'code', label: 'Call number / code', type: 'text' },
      { name: 'items', label: 'Skills (comma separated)', type: 'textarea' },
    ],
  },
  {
    key: 'projects',
    label: 'Projects',
    type: 'list',
    table: 'projects',
    searchFields: ['title', 'summary', 'tags'],
    primary: 'title',
    secondary: 'period',
    fields: [
      { name: 'code', label: 'Call number / code', type: 'text' },
      { name: 'title', label: 'Title', type: 'text', required: true },
      { name: 'period', label: 'Period', type: 'text' },
      { name: 'summary', label: 'Summary', type: 'textarea' },
      { name: 'tags', label: 'Tags (comma separated)', type: 'text' },
      { name: 'link', label: 'Link URL', type: 'text' },
      { name: 'link_label', label: 'Link label', type: 'text' },
    ],
  },
  {
    key: 'experience',
    label: 'Experience',
    type: 'list',
    table: 'experience',
    orderField: 'sort_order',
    orderAscending: true,
    searchFields: ['role', 'org', 'period'],
    primary: 'role',
    secondary: 'org',
    fields: [
      { name: 'role', label: 'Role', type: 'text', required: true },
      { name: 'org', label: 'Organization', type: 'text' },
      { name: 'period', label: 'Period', type: 'text' },
      { name: 'location', label: 'Location', type: 'text' },
      { name: 'code', label: 'Call number / code', type: 'text' },
      { name: 'points', label: 'Bullet points (one per line)', type: 'textarea', rows: 4 },
    ],
  },
  {
    key: 'research',
    label: 'Research',
    type: 'list',
    table: 'research_interests',
    searchFields: ['title', 'description', 'code'],
    primary: 'title',
    secondary: 'code',
    fields: [
      { name: 'code', label: 'Classification code', type: 'text' },
      { name: 'title', label: 'Title', type: 'text', required: true },
      { name: 'description', label: 'Description', type: 'textarea' },
    ],
  },
  {
    key: 'gallery',
    label: 'Gallery',
    type: 'list',
    table: 'gallery',
    orderField: 'sort_order',
    orderAscending: true,
    searchFields: ['caption', 'category'],
    primary: 'caption',
    secondary: 'category',
    isImageGrid: true,
    fields: [
      { name: 'src', label: 'Image', type: 'image', bucket: 'gallery-photos', required: true },
      { name: 'caption', label: 'Caption', type: 'text', required: true },
      { name: 'category', label: 'Category', type: 'text' },
    ],
  },
  {
    key: 'certifications',
    label: 'Certifications',
    type: 'list',
    table: 'certifications',
    orderField: 'sort_order',
    orderAscending: true,
    searchFields: ['title', 'issuer'],
    primary: 'title',
    secondary: 'issuer',
    note: "There's no Certifications section on the public site yet — this data is ready and waiting whenever you'd like one added.",
    fields: [
      { name: 'title', label: 'Title', type: 'text', required: true },
      { name: 'issuer', label: 'Issuer', type: 'text' },
      { name: 'date', label: 'Date', type: 'text' },
      { name: 'credential_url', label: 'Credential URL', type: 'text' },
      { name: 'image_url', label: 'Badge / certificate image', type: 'image', bucket: 'site-media' },
    ],
  },
  {
    key: 'social',
    label: 'Social Links',
    type: 'list',
    table: 'social_links',
    orderField: 'sort_order',
    orderAscending: true,
    searchFields: ['platform', 'url'],
    primary: 'platform',
    secondary: 'url',
    fields: [
      {
        name: 'platform',
        label: 'Platform',
        type: 'select',
        options: ['linkedin', 'github', 'scholar', 'researchgate', 'orcid', 'twitter', 'website'],
        required: true,
      },
      { name: 'url', label: 'URL', type: 'text', required: true },
    ],
  },
  {
    key: 'blog',
    label: 'Blog',
    type: 'list',
    table: 'blog_posts',
    orderField: 'date',
    orderAscending: false,
    searchFields: ['title', 'category', 'excerpt'],
    primary: 'title',
    secondary: 'category',
    slugFrom: 'title',
    linkPreview: (row) => `#/blog/${row.slug}`,
    fields: [
      { name: 'title', label: 'Title', type: 'text', required: true },
      { name: 'category', label: 'Category', type: 'text' },
      { name: 'date', label: 'Date', type: 'date' },
      { name: 'accent', label: 'Accent color', type: 'colorSwatch', options: ACCENTS },
      { name: 'excerpt', label: 'Excerpt', type: 'text' },
      { name: 'content', label: 'Content (blank line = new paragraph)', type: 'textarea', rows: 8 },
    ],
  },
  {
    key: 'contact',
    label: 'Contact Information',
    type: 'singleton',
    table: 'contact',
    note: 'Social icons live under the separate "Social Links" tab, not here.',
    fields: [
      { name: 'heading', label: 'Section heading', type: 'text' },
      { name: 'blurb', label: 'Blurb', type: 'textarea' },
      { name: 'email', label: 'Email', type: 'text' },
      { name: 'phone', label: 'Phone', type: 'text' },
      { name: 'location', label: 'Location', type: 'text' },
    ],
  },
  {
    key: 'resume',
    label: 'Resume / CV',
    type: 'singleton',
    table: 'site_settings',
    fields: [{ name: 'resume_url', label: 'Résumé / CV file (PDF)', type: 'file', bucket: 'site-media', accept: 'application/pdf' }],
  },
  {
    key: 'footer',
    label: 'Footer',
    type: 'singleton',
    table: 'site_settings',
    fields: [
      { name: 'footer_tagline', label: 'Footer tagline (after the copyright name)', type: 'text' },
      { name: 'footer_note', label: 'Footer note (e.g. "Built with…")', type: 'text' },
    ],
  },
  {
    key: 'settings',
    label: 'Website Settings',
    type: 'singleton',
    table: 'site_settings',
    fields: [
      { name: 'site_title', label: 'Site title (browser tab)', type: 'text' },
      { name: 'meta_description', label: 'Meta description (SEO)', type: 'textarea' },
    ],
  },
]
